spring:
  redis:
    port: 6379
    ssl: true
    host: master.testredis.drglxu.cnw1.cache.amazonaws.com.cn
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
      shutdown-timeout: 100ms